version: "3.3"
services:
  samba:
    container_name: samba
    image: samba:latest
    volumes:
      - ./smb.conf:/etc/samba/smb.conf
      - ./config:/etc/samba
      - /mnt/admin_share:/mnt/admin_share
      - /mnt/madhu_share:/mnt/madhu_share
    ports:
      - 445:445
      - 139:139
    environment:
      - user_count=2
      - user1=admin
      - password1=1234
      - user2=madhu
      - password2=4321
    restart: always